# Generated by Django 6.0.3 on 2026-04-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10)),
                ('to_currency', models.CharField(default='NPR', max_length=10)),
                ('amount', models.FloatField()),
                ('converted_amount', models.FloatField()),
                ('conversion_rate', models.FloatField()),
            ],
        ),
    ]
