# Generated by Django 6.0.4 on 2026-04-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyconversion',
            name='conversion_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currencyconversion',
            name='converted_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currencyconversion',
            name='to_currency',
            field=models.CharField(max_length=10),
        ),
    ]
