# Generated by Django 5.2.13 on 2026-06-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0002_alter_currencyconversion_conversion_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyconversion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
